# Generated by Django 4.2.5 on 2023-10-04 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_no', models.CharField(max_length=15)),
                ('designation', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('Trainee', 'Trainee'), ('Associate', 'Associate'), ('Consultant', 'Consultant'), ('Senior Associate', 'Senior Associate'), ('Manager', 'Manager')], max_length=20)),
                ('department', models.CharField(choices=[('SAC', 'SAC'), ('Engineering', 'Engineering'), ('SAP SD', 'SAP SD'), ('SAP PP', 'SAP PP'), ('SAP MM', 'SAP MM'), ('SAP FICO', 'SAP FICO'), ('SAP ABAP', 'SAP ABAP')], max_length=20)),
                ('reporting_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_name', to='profiles.employee')),
            ],
        ),
    ]
