# Generated by Django 4.2.5 on 2023-10-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('employee_email', models.EmailField(max_length=254)),
                ('mobile_no', models.CharField(max_length=15)),
                ('designation', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('Trainee', 'Trainee'), ('Associate', 'Associate'), ('Consultant', 'Consultant'), ('Senior Associate', 'Senior Associate'), ('Manager', 'Manager')], max_length=20)),
            ],
        ),
    ]
