# Generated by Django 4.2.5 on 2023-10-02 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0002_rename_employee_email_employee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='reporting_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_id', to='employeeapp.employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='reporting_manager_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_name', to='employeeapp.employee'),
        ),
    ]
