# Generated by Django 4.2.5 on 2023-10-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0004_remove_employee_reporting_manager_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('SAC', 'SAC'), ('Engineering', 'Engineering'), ('SAP SD', 'SAP SD'), ('SAP PP', 'SAP PP'), ('SAP MM', 'SAP MM'), ('SAP FICO', 'SAP FICO'), ('SAP ABAP', 'SAP ABAP')], max_length=20),
        ),
    ]
