# Generated by Django 4.2.5 on 2023-09-27 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=250)),
                ('module_description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket', models.AutoField(primary_key=True, serialize=False)),
                ('ticket_description', models.CharField(max_length=250)),
                ('reporter', models.CharField(max_length=100)),
                ('reporter_contact', models.CharField(max_length=10)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Show Stopper', 'Show Stopper')], max_length=50)),
                ('category', models.CharField(choices=[('Technical', 'Technical'), ('Functional', 'Functional'), ('Error Messages', 'Error Messages'), ('Reporting, Analytics and Forms', 'Reporting, Analytics and Forms'), ('Custom Development', 'Custom Development')], max_length=50)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheetapp.module')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheetapp.project')),
            ],
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('timesheet', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(null=True)),
                ('starttime', models.DateTimeField()),
                ('endtime', models.DateTimeField()),
                ('effort_description', models.CharField(max_length=250)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheetapp.project')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='your_ticket', to='timesheetapp.ticket')),
            ],
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('category',), name='unique_category'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.CheckConstraint(check=models.Q(('category__in', ['Technical', 'Functional', 'Error Messages', 'Reporting, Analytics and Forms', 'Custom Development'])), name='valid_category_check'),
        ),
    ]
