# Generated by Django 4.2.5 on 2023-09-29 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheetapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='approval_status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('In Dispute', 'In Dispute')], default='', max_length=20),
        ),
    ]
