# Generated by Django 4.2.5 on 2023-09-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheetapp', '0002_timesheet_approval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='approval_status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('In Dispute', 'In Dispute')], default='In Progress', max_length=20),
        ),
    ]
