# Generated by Django 4.2.5 on 2023-09-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheetapp', '0003_alter_timesheet_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='total_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
