# Generated by Django 4.2.5 on 2023-09-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheetapp', '0004_timesheet_total_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='billable_status',
            field=models.CharField(choices=[('Billable', 'Billable'), ('Non Billable', 'Non Billable')], default='Billable', max_length=20),
        ),
    ]
