# Generated by Django 4.2.5 on 2023-09-30 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheetapp', '0006_dispute'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='disputed',
            field=models.BooleanField(default=False),
        ),
    ]
