# Generated by Django 4.2.5 on 2023-09-30 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheetapp', '0007_timesheet_disputed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='disputed',
        ),
    ]
