# Generated by Django 4.2.5 on 2023-09-30 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timesheetapp', '0009_employee_remove_timesheet_total_hours_delete_dispute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='approval_status',
            field=models.CharField(choices=[('', ''), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='raised_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheetapp.employee'),
        ),
    ]
