# Generated by Django 4.2.5 on 2023-10-01 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0001_initial'),
        ('timesheetapp', '0010_alter_timesheet_approval_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='your_ticket', to='ticketapp.ticket'),
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
