# Generated by Django 4.2.5 on 2023-10-01 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
        ('ticketapp', '0002_alter_ticket_project'),
        ('employeeapp', '0001_initial'),
        ('timesheetapp', '0011_alter_timesheet_ticket_delete_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='billable_status',
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.project'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='raised_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeapp.employee'),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
