# Generated by Django 4.2.5 on 2023-10-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheetapp', '0012_remove_timesheet_billable_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='title',
            field=models.CharField(default='', max_length=20),
        ),
    ]
