# Generated by Django 4.2.5 on 2023-10-02 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheetapp', '0014_alter_timesheet_endtime_alter_timesheet_starttime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='project',
        ),
    ]
