# Generated by Django 4.2.5 on 2023-10-04 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        ('profiles', '0001_initial'),
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('timesheet', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(null=True)),
                ('starttime', models.TimeField()),
                ('endtime', models.TimeField()),
                ('title', models.CharField(max_length=20)),
                ('effort_description', models.CharField(max_length=250)),
                ('approval_status', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.employee')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='your_ticket', to='ticket.ticket')),
            ],
        ),
    ]
