# Generated by Django 4.2.5 on 2023-10-06 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        ('ticket', '0001_initial'),
        ('profiles', '0003_user_username'),
        ('timesheet', '0002_alter_timesheet_endtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worklog',
            fields=[
                ('worklog', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(null=True)),
                ('starttime', models.TimeField()),
                ('endtime', models.TimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=20)),
                ('effort_description', models.CharField(max_length=250)),
                ('approval_status', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.user')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='your_ticket', to='ticket.ticket')),
            ],
        ),
        migrations.DeleteModel(
            name='Timesheet',
        ),
    ]
