# Generated by Django 4.2.5 on 2023-10-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0003_worklog_delete_timesheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklog',
            name='approval_status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=20),
        ),
    ]
