# Generated by Django 4.2.5 on 2023-10-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0004_alter_worklog_approval_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worklog',
            name='approval_status',
        ),
        migrations.AddField(
            model_name='worklog',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Submitted', max_length=20),
        ),
    ]
