# Generated by Django 4.2.5 on 2023-10-13 11:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0005_remove_worklog_approval_status_worklog_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worklog',
            old_name='effort_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='worklog',
            old_name='raised_by',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='worklog',
            name='date',
        ),
        migrations.RemoveField(
            model_name='worklog',
            name='endtime',
        ),
        migrations.RemoveField(
            model_name='worklog',
            name='starttime',
        ),
        migrations.RemoveField(
            model_name='worklog',
            name='status',
        ),
        migrations.AddField(
            model_name='worklog',
            name='end_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='worklog',
            name='start_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
