# Generated by Django 4.2.5 on 2023-10-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0007_alter_worklog_end_date_alter_worklog_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklog',
            name='end_date',
            field=models.DateTimeField(),
        ),
    ]
