# Generated by Django 4.2.5 on 2023-10-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0008_alter_worklog_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklog',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
