# Generated by Django 4.2.5 on 2023-10-13 11:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0009_alter_worklog_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklog',
            name='event_date',
            field=models.DateField(default=datetime.date(2023, 10, 13)),
        ),
    ]
