# Generated by Django 4.2.5 on 2023-10-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0010_worklog_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklog',
            name='description',
            field=models.TextField(),
        ),
    ]
