# Generated by Django 4.2.5 on 2023-10-13 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0011_alter_worklog_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worklog',
            name='event_date',
        ),
    ]
