# Generated by Django 4.2.5 on 2023-10-04 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket', models.AutoField(primary_key=True, serialize=False)),
                ('ticket_description', models.CharField(max_length=250)),
                ('reporter_name', models.CharField(max_length=100)),
                ('reporter_email', models.CharField(max_length=100)),
                ('reporter_contact', models.CharField(max_length=10)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Show Stopper', 'Show Stopper')], max_length=50)),
                ('category', models.CharField(choices=[('Technical', 'Technical'), ('Functional', 'Functional'), ('Error Messages', 'Error Messages'), ('Reporting, Analytics and Forms', 'Reporting, Analytics and Forms'), ('Custom Development', 'Custom Development')], max_length=50)),
                ('module', models.CharField(choices=[('SAP SD', 'SAP SD'), ('SAP PP', 'SAP PP'), ('SAP MM', 'SAP MM'), ('SAP FICO', 'SAP FICO'), ('SAP ABAP', 'SAP ABAP')], max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
    ]
